server:
  port: 8001


spring:
  application:
    name: storefront-bff
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/ShopSphere
        registration:
          keycloak:
            provider: keycloak
            client-id: edge-service
            client-secret: YUAKMdYBO7tCdloiQmQUwmWJDFTkxI8c
            scope: openid, profile, email, roles
  data:
    redis:
      host: localhost
      port: 6379
  # Use redis to save session
  session:
    store-type: redis
  cloud:
    gateway:
      default-filters:
        - SaveSession
        - TokenRelay
      routes:
        - id: customer-route
          uri: http://localhost:9001
          predicates:
            - Path=customer/storefront/**



service-url:
  service:
    customer: http://localhost:9001/storefront
    token: http://localhost:8080/realms/ShopSphere/protocol/openid-connect/token