server:
  port: 9003
  servlet:
    context-path: /order

spring:
  application:
    name: order-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/ShopSphere
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgres://localhost:5432/ecommerce_db
    username: admin
    password: admin

service:
  product: http://localhost:9002/product